### ISSUE TITLE
Can't seem to use exclude-current config option

### ISSUE THREAD

**Issue by dwvisser** [vegardit/fast-apt-mirror.sh#10]
My repository's CI workflow fails a test due to the failure much of the time to pull certain packages from the default Azure mirror for Ubuntu-20.04. I have attempted to add the config key `exclude-current` to prevent it from using the Azure Mirror. Here is my job config:

```yaml
      - name: Configure Fast APT Mirror and Run APT Update
        uses: vegardit/fast-apt-mirror.sh@v1
        with:
          exclude-current: ${{ true }}
``` 

Nothing changes in my run, i.e., the existing default is still considered with the random list of mirrors. Well, one thing changes: I see this error message as the last line of output:

```
  /home/runner/work/_temp/425b8fff-947e-4137-8b66-bda410b2d75f.sh: line 29: --exclude-current: command not found
```

Am I using it wrong?
